web:
  build: ./virtualization/app
  command: server:run 0.0.0.0:8000 -vvv
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - .:/code
composer:
  build: ./virtualization/composer
  volumes:
    - .:/app
db:
  build: ./virtualization/db
  ports:
    - "5432:5432"

  volumes:
    - ./virtualization/db:/docker-entrypoint-initdb.d/
