web:
  build: .
  command: php /code/app/console server:run 0.0.0.0:8000 -vvv
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - .:/code
db:
  build: ./docker_db
  ports:
    - "5432:5432"
