OpenMarket\APIBundle\Entity\User:
    type: entity
    table: user
    readOnly: false
    id:
        id:
            type: string
            length: 36
            generator:
                strategy: auto
    fields:
        username:
            type: string
            column: username
            length: 50
        password:
            type: string
            column: password
            length: 255
        salt:
            type: string
            column: salt
            length: 255
        firstName:
            type: string
            column: first_name
            length: 50
        lastName:
            type: string
            column: last_name
            length: 50
