OpenMarket\APIBundle\Entity\User:
    type: entity
    table: user
    readOnly: false
    id:
        id:
            type: string
            length: 50
            generator:
                strategy: None
    fields:
        firstName:
            type: string
            column: first_name
            length: 50
        lastName:
            type: string
            column: last_name
            length: 50