jms_serializer:
    metadata:
        auto_detection: false
        directories:
            APIBundle:
                namespace_prefix: "OpenMarket\\APIBundle"
                path: "@OpenMarketAPIBundle/Resources/config/serializer"