jms_serializer:
    metadata:
        auto_detection: false
        directories:
            Authentication:
                namespace_prefix: "OpenMarket\\Authentication"
                path: "@OpenMarketAPIBundle/Resources/config/serializer/"