nelmio_api_doc:
    sandbox:
        authentication:
            name: Authorization
            delivery: header
            type: bearer
        accept_type: application/json
        body_format:
            formats: [json]
            default_format: json

        request_format:
            formats:
                json: application/json
