security:
    providers:
        in_memory:
            memory: ~

    firewalls:

        login:
            pattern:  ^/api/tokens
            stateless: true
            anonymous: true
            gfreeau_get_jwt:
                username_parameter: username
                password_parameter: password
                post_only: true
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt: ~

        default:
            anonymous: ~

    access_control:
        - { path: ^/api/tokens, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
