OpenMarket\APIBundle\Entity\User:
    properties:
        firstName:
            - NotBlank: { groups: [View] }
            - Length: { min: 3, groups: [View] }

        lastName:
            - NotBlank: { groups: [View] }
            - Length: { min: 3, groups: [View] }

