OpenMarket\APIBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            since_version: 1.0
            expose: true
            inline: true
            type: OpenMarket\APIBundle\Entity\UserId
            groups: [Default]
        firstName:
            since_version: 1.0
            expose: true
            type: string
            serialized_name: first_name
            groups: [Default,Create]
        lastName:
            since_version: 1.0
            expose: true
            type: string
            serialized_name: last_name
            groups: [Default,Create]

