OpenMarket\APIBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            inline: true
            serialized_name: id
            type: OpenMarket\APIBundle\Entity\UserId
            groups: [default]
        firstName:
            expose: true
            serialized_name: first_name
            groups: [default]
        lastName:
            expose: true
            serialized_name: last_name
            groups: [default]