camion:
    type:     rest
    resource: OpenMarket\APIBundle\Controller\DefaultController

users:
  type:     rest
  resource: OpenMarket\APIBundle\Controller\UserController

tokens:
  type:     rest
  resource: OpenMarket\APIBundle\Controller\TokenController

