parameters:
    api_bundle.db.table_prefix: api_
services:
    api_bundle.tblprefix_subscriber:
        class: OpenMarket\APIBundle\Subscriber\TablePrefixSubscriber
        arguments: [%api_bundle.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }

    base_user_repository:
        class: Doctrine\ORM\EntityManager
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        public: false
        arguments:
            - OpenMarket\APIBundle\Entity\User

    user_repository:
        class: OpenMarket\APIBundle\Repository\Doctrine\UserRepository
        arguments:
            - @doctrine.orm.entity_manager
            - @base_user_repository

    jms_serializer.object_constructor:
        alias: jms_serializer.initialized_object_constructor
        public: false

    jms_serializer.initialized_object_constructor:
         class: OpenMarket\APIBundle\Service\InitializedObjectConstructor
         arguments:
            - @jms_serializer.doctrine_object_constructor

#    open_market_api.example:
#        class: OpenMarket\APIBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
